from circil.fuzzer.config import FuzzerConfig
from circil.ir.operator import Operator
from circil.ir.type import IRType
from circil.rewrite.rule import Rule
from zkvm_fuzzer_utils.risc32_im import RISCV_IM_EXTENSION

INPUT_LOOP_ITERATIONS = 3

MIN_VALUE_U32 = 0
MAX_VALUE_U32 = 2**32 - 1

MIN_FUZZER_BATCH_SIZE = 2
MAX_FUZZER_BATCH_SIZE = 10

MIN_FUZZER_REWRITES = 1
MAX_FUZZER_REWRITES = 4

FUZZER_ITERATIVE_REWRITE = True

FUZZER_CONFIG = FuzzerConfig(
    probability_weight_constant=1,
    probability_weight_identifier=1,
    probability_weight_unary=1,
    probability_weight_binary=1,
    probability_weight_ternary=1,
    probability_weight_compare=1,
    probability_weight_custom=1,
    max_expression_depth=5,
    min_assertions=0,
    max_assertions=0,
    min_circuit_input_signals=1,
    max_circuit_input_signals=12,  # 12 is max value because of rust tuples
    min_circuit_output_signals=1,
    max_circuit_output_signals=12,  # 12 is max value because of rust tuples
    enable_constant_exponent=False,
    min_exponent_value=0,
    max_exponent_value=0,
    probability_boundary_value=0.3,
    disable_field_modulo_boundary_value=True,
    comparators=[
        Operator.EQU,
        Operator.NEQ,
        Operator.LTH,
        Operator.LEQ,
        Operator.GTH,
        Operator.GEQ,
    ],
    boolean_unary_operators=[Operator.NOT],
    boolean_binary_operators=[Operator.LAND, Operator.LOR, Operator.LXOR],
    arithmetic_unary_operators=[Operator.COMP],  # Operator.SUB
    arithmetic_binary_operators=[
        Operator.ADD,
        Operator.SUB,
        Operator.MUL,
        Operator.POW,
        Operator.DIV,
        Operator.REM,
        Operator.AND,
        Operator.OR,
        Operator.XOR,
    ],
    ternary_expression_types=[IRType.Field, IRType.Bool],
    input_signal_types=[IRType.Field, IRType.Bool],
    output_signal_types=[IRType.Field, IRType.Bool],
    enable_divisor_assertion=False,
    enable_divisor_non_zero_constant=True,
    custom_functions=RISCV_IM_EXTENSION,
)

REWRITE_RULES = [
    Rule("comm-or", "(?a | ?b)", "(?b | ?a)"),
    Rule("assoc-and", "((?a & ?b) & ?c)", "(?a & (?b & ?c))"),
    Rule("comm-and", "(?a & ?b)", "(?b & ?a)"),
    Rule("and-zero", "(?a & 0)", "0"),
    Rule("inv-xor", "(?a ^ ?a)", "0"),
    Rule("comm-xor", "(?a ^ ?b)", "(?b ^ ?a)"),
    Rule("zero-or-rev", "(?a | 0)", "?a"),
    Rule("zero-xor-rev", "(?a ^ 0)", "?a"),
    Rule("inv-xor-rev", "0", "($r:int ^ $r:int)"),
    Rule("zero-or", "?a:int", "(?a | 0)"),
    Rule("zero-xor", "?a:int", "(?a ^ 0)"),
    Rule("idem-and", "?a:int", "(?a & ?a)"),
    Rule("zero-and", "0", "($r:int & 0)"),
    Rule("one-div", "1", "($r:int / $r:int)"),
    Rule("comm-add", "(?a + ?b)", "(?b + ?a)"),
    Rule("comm-mul", "(?a * ?b)", "(?b * ?a)"),
    Rule("dist-mul-add", "((?a + ?b) * ?c)", "((?a * ?c) + (?b * ?c))"),
    Rule("dist-add-mul", "((?a * ?c) + (?b * ?c))", "((?a + ?b) * ?c)"),
    Rule("assoc-add", "((?a + ?b) + ?c)", "(?a + (?b + ?c))"),
    Rule("assoc-add-rev", "(?a + (?b + ?c))", "((?a + ?b) + ?c)"),
    Rule("assoc-mul", "((?a * ?b) * ?c)", "(?a * (?b * ?c))"),
    Rule("assoc-mul-rev", "(?a * (?b * ?c))", "((?a * ?b) * ?c)"),
    Rule("zero-add-des", "(?a + 0)", "?a"),
    Rule("one-mul-des", "(?a * 1)", "?a"),
    Rule("one-div-des", "(?a / 1)", "?a"),
    Rule("inv-zero-add-des", "(?a - 0)", "?a"),
    Rule("inv-add-des", "(?a - ?a)", "0"),
    Rule("inv-assoc-neg2pos", "((?a - ?b) - ?c)", "(?a - (?b + ?c))"),
    Rule("inv-assoc-pos2neg", "(?a - (?b + ?c))", "((?a - ?b) - ?c)"),
    Rule("pow2_to_mul", "(?a ** 2)", "(?a * ?a)"),
    Rule("pow3_to_mul", "(?a ** 3)", "((?a * ?a) * ?a)"),
    Rule("mul_to_pow2", "(?a * ?a)", "(?a ** 2)"),
    Rule("mul_to_pow3", "((?a * ?a) * ?a)", "(?a ** 3)"),
    Rule("zero-add-con", "?a:int", "(?a + 0)"),
    Rule("one-mul-con", "?a:int", "(?a * 1)"),
    Rule("one-div-con", "?a:int", "(?a / 1)"),
    Rule("rem-of-one-con", "0", "($r:int % 1)"),
    Rule("rem-of-one-des", "(?a:int % 1)", "0"),
    Rule("and-to-rem", "(?a:int & 1)", "(?a % 2)"),
    Rule("rem-to-and", "(?a:int % 2)", "(?a & 1)"),
    Rule("inv-zero-add-con", "?a:int", "(?a - 0)"),
    Rule("inv_addition_exp", "(?a - ?c)", "(?a + (0 - ?c))"),
    Rule("double-negation-add-con", "?a:int", "(0 - (0 - ?a))"),
    Rule("add_sub_random_value", "?a:int", "((?a - $r:int) + $r:int)"),
    Rule("zero-lor-des", "(?a || F)", "?a"),
    Rule("zero-land-des", "(?a && T)", "?a"),
    Rule("taut-lor", "(?a || T)", "T"),
    Rule("contra-land", "(?a && F)", "F"),
    Rule("assoc-lor", "((?a || ?b) || ?c)", "(?a || (?b || ?c))"),
    Rule("assoc-land", "((?a && ?b) && ?c)", "(?a && (?b && ?c))"),
    Rule("comm-lor", "(?a || ?b)", "(?b || ?a)"),
    Rule("comm-lan", "(?a && ?b)", "(?b && ?a)"),
    Rule("dist-lor-land", "((?a && ?b) || ?c)", "((?a || ?c) && (?b || ?c))"),
    Rule("dist-land-lor", "((?a || ?c) && (?b || ?c))", "((?a && ?b) || ?c)"),
    Rule("de-morgan-land-con", "(!(?a && ?b))", "((!?a) || (!?b))"),
    Rule("de-morgan-land-des", "((!?a) || (!?b))", "(!(?a && ?b))"),
    Rule("de-morgan-lor-con", "(!(?a || ?b))", "((!?a) && (!?b))"),
    Rule("de-morgan-lor-des", "((!?a) && (!?b))", "(!(?a || ?b))"),
    Rule("double-negation-des", "(!(!?a))", "?a"),
    Rule("double-land-des", "(?a && ?a)", "?a:bool"),
    Rule("double-lor-des", "(?a || ?a)", "?a:bool"),
    Rule("double-lxor-des", "(?a ^^ ?a)", "F"),
    Rule("comm-lxor", "(?a ^^ ?b)", "(?b ^^ ?a)"),
    Rule("lxor-to-or-and", "(?a ^^ ?b)", "(((!?a) && ?b) || (?a && (!?b)))"),
    Rule("zero-lor-con", "?a:bool", "(?a || F)"),
    Rule("zero-land-con", "?a:bool", "(?a && T)"),
    Rule("double-negation-con", "?a:bool", "(!(!?a))"),
    Rule("double-land-con", "?a:bool", "(?a && ?a)"),
    Rule("double-lor-con", "?a:bool", "(?a || ?a)"),
    Rule("double-lxor-con", "F", "($r:bool ^^ $r:bool)"),
    Rule("or-and-to-lxor", "(((!?a) && ?b) || (?a && (!?b)))", "(?a ^^ ?b)"),
    Rule("commutativity-equ", "(?a == ?b)", "(?b == ?a)"),
    Rule("relation-geq-to-leq", "(?a >= ?b)", "(?b <= ?a)"),
    Rule("relation-leq-to-geq", "(?a <= ?b)", "(?b >= ?a)"),
    Rule("relation-leq-to-lth-and-equ", "(?a <= ?b)", "((?a < ?b) || (?a == ?b))"),
    Rule("relation-lth-and-equ-to-leq", "((?a < ?b) || (?a == ?b))", "(?a <= ?b)"),
    Rule("relation-geq-to-gth-and-equ", "(?a >= ?b)", "((?a > ?b) || (?a == ?b))"),
    Rule("relation-gth-and-equ-to-geq", "((?a > ?b) || (?a == ?b))", "(?a >= ?b)"),
    Rule("relation-leq-to-not-gth", "(?a <= ?b)", "(!(?a > ?b))"),
    Rule("relation-not-gth-to-leq", "(!(?a > ?b))", "(?a <= ?b)"),
    Rule("relation-geq-to-not-lth", "(?a >= ?b)", "(!(?a < ?b))"),
    Rule("relation-not-lth-to-geq", "(!(?a < ?b))", "(?a >= ?b)"),
    Rule("relation-neq-to-not-equ", "(?a != ?b)", "(!(?a == ?b))"),
    Rule("relation-not-equ-to-neq", "(!(?a == ?b))", "(?a != ?b)"),
]
