# ---------------------------------------------------------------------------- #
#                                   Constants                                  #
# ---------------------------------------------------------------------------- #

: "${SLEEP_BETWEEN_PODMAN_STARTUPS:=10}"
: "${NAMESPACE_POSTFIX:=}"

# ---------------------------------------------------------------------------- #
#                                   Variables                                  #
# ---------------------------------------------------------------------------- #

DOCKERFILE="$ROOT_DIR/projects/$ZKVM_NAME-fuzzer/Dockerfile"
NAME_TAG="${COMMIT_OR_BRANCH:0:7}$NAMESPACE_POSTFIX"

IMAGE_NAME="zkvm/$ZKVM_NAME"
CONTAINER_NAME="zkvm-$ZKVM_NAME-fuzzer-$NAME_TAG"

OUT_DIR="$ROOT_DIR/out"
BASE_DIR="$OUT_DIR/$ZKVM_NAME"
NAMESPACE_DIR="$BASE_DIR/$NAME_TAG"
DOT_DIR="$NAMESPACE_DIR/dot"
DOT_CARGO="$DOT_DIR/cargo"
DOT_RUSTUP="$DOT_DIR/rustup"
DOT_ZKVM="$DOT_DIR/$ZKVM_NAME"
LIB_DIR="$NAMESPACE_DIR/lib"
ZKVM_REPO="$LIB_DIR/$ZKVM_NAME"
WORKSPACE_DIR="$NAMESPACE_DIR/workspace"
LOGS_DIR="$WORKSPACE_DIR/logs"

# relevant checker script to validate refinding
FINDINGS_NAME_TAG="${FINDINGS_COMMIT_OR_BRANCH:0:7}$FINDINGS_NAMESPACE_POSTFIX"
FINDINGS_NAMESPACE_DIR="$BASE_DIR/$FINDINGS_NAME_TAG"
FINDINGS_CSV="$FINDINGS_NAMESPACE_DIR/workspace/findings.csv"

# ---------------------------------------------------------------------------- #
#                                 Podman Helper                                #
# ---------------------------------------------------------------------------- #

create_folder_structure() {
    mkdir -p "$OUT_DIR"
    mkdir -p "$BASE_DIR"
    mkdir -p "$NAMESPACE_DIR"
    mkdir -p "$DOT_DIR"
    mkdir -p "$DOT_CARGO"
    mkdir -p "$DOT_RUSTUP"
    mkdir -p "$DOT_ZKVM"
    mkdir -p "$LIB_DIR"
    mkdir -p "$ZKVM_REPO"
    mkdir -p "$WORKSPACE_DIR"

    rm -rf "$LOGS_DIR"
    mkdir -p "$LOGS_DIR"

    rm -rf "$WORKSPACE_DIR"/*.csv
    rm -rf "$WORKSPACE_DIR"/findings 
}

# ---------------------------------------------------------------------------- #

build_image() {
    local flags=(
        --volume "$DOT_CARGO":/root/.cargo
        --volume "$DOT_RUSTUP":/root/.rustup
        --volume "$DOT_ZKVM:/root/.$ZKVM_NAME"
        --ulimit=nproc=65535
        --ulimit=nofile=65535
        --tag "$IMAGE_NAME"
        --file "$DOCKERFILE"
        --logfile "$LOGS_DIR/podman-build.log"
    )

    # NOTE: If .cargo or .rustup is empty it is a strong indicator that we need to build
    #       without cache. This is because the image does not know about file changes on
    #       mounted volumes.
    if { [[ -d "$DOT_CARGO" ]] && [[ -z "$(ls -A "$DOT_CARGO" 2>/dev/null)" ]]; } || \
       { [[ -d "$DOT_RUSTUP" ]] && [[ -z "$(ls -A "$DOT_RUSTUP" 2>/dev/null)" ]]; }; then
        flags+=("--no-cache")
    fi

    echo "building podman image $IMAGE_NAME for $NAME_TAG ..."
    podman build "${flags[@]}" "$ROOT_DIR"
    echo "building podman image $IMAGE_NAME for $NAME_TAG ... done!"
}

# ---------------------------------------------------------------------------- #

install_and_modify_vm() {
    local podman_flags=(
        --volume "$DOT_CARGO":/root/.cargo
        --volume "$DOT_RUSTUP":/root/.rustup
        --volume "$DOT_ZKVM":/root/."$ZKVM_NAME"
        --volume "$ZKVM_REPO":/root/"$ZKVM_NAME"
        --volume "$WORKSPACE_DIR":/root/workspace
        --name "$CONTAINER_NAME"
        --rm
        --pids-limit -1
        "$IMAGE_NAME"
    )

    local installer_flags=(
        "/root/$ZKVM_NAME"
        --verbosity "$VERBOSITY"
        --log-file logs/installer.log
        --commit-or-branch "$COMMIT_OR_BRANCH"
    )
    [[ $ZKVM_MODIFICATION == true ]] && installer_flags+=("--zkvm-modification")

    echo "installing $ZKVM_NAME for $NAME_TAG ..."
    podman run "${podman_flags[@]}" "$ZKVM_NAME-fuzzer" install "${installer_flags[@]}"
    echo "installing $ZKVM_NAME for $NAME_TAG ... done!"
}

# ---------------------------------------------------------------------------- #

run_fuzzer_with_id_and_seed() {
    # NOTE: Sharing .cargo folders lead to weird I/O and blocking issues.
    #       This section takes the .cargo folder generated by the image
    #       generation and copies it to a new location specific for the current
    #       pod.
    local dot_cargo_for_id="$DOT_CARGO"
    if [[ $1 -gt 1 ]]; then
        cargo_id=$(($1-1))
        dot_cargo_for_id="$DOT_CARGO-$cargo_id"
        rm -rf "$dot_cargo_for_id"
        cp -r "$DOT_CARGO" "$dot_cargo_for_id"
    fi

    local podman_flags=(
        --volume "$dot_cargo_for_id":/root/.cargo
        --volume "$DOT_RUSTUP":/root/.rustup
        --volume "$DOT_ZKVM":/root/."$ZKVM_NAME"
        --volume "$ZKVM_REPO":/root/"$ZKVM_NAME"
        --volume "$WORKSPACE_DIR":/root/workspace
        --name "$CONTAINER_NAME-$1"
        --rm
        --cpus="$PODMAN_CPUS"
        --pids-limit -1
        "$IMAGE_NAME"
    )

    local fuzzer_flags=(
        --verbosity "$VERBOSITY"
        --out "$1"
        --seed "$2"
        --zkvm "/root/$ZKVM_NAME"
        --log-file logs/fuzzer-"$1".log
        --commit-or-branch "$COMMIT_OR_BRANCH"
    )
    [[ $TRACE_COLLECTION == true ]] && fuzzer_flags+=(--trace-collection)
    [[ $FAULT_INJECTION == true ]] && fuzzer_flags+=(--fault-injection)
    [[ $FUZZER_TIMEOUT =~ ^[0-9]+$ ]] && fuzzer_flags+=(--timeout "$FUZZER_TIMEOUT")
    [[ $ONLY_MOD_WORD == true ]] && fuzzer_flags+=(--only-modify-word)
    [[ $NO_INLINE_ASSEMBLY == true ]] && fuzzer_flags+=(--no-inline-assembly)
    [[ $NO_SCHEDULAR == true ]] && fuzzer_flags+=(--no-schedular)

    echo "start $ZKVM_NAME-$NAME_TAG-$1 fuzzer with seed: $2"
    podman run "${podman_flags[@]}" "$ZKVM_NAME-fuzzer" run "${fuzzer_flags[@]}"
}

# ---------------------------------------------------------------------------- #
#                                   Functions                                  #
# ---------------------------------------------------------------------------- #

install() {
    create_folder_structure
    build_image
    install_and_modify_vm
}

# ---------------------------------------------------------------------------- #

explore() {
    local prod_pids=()
    local pid

    for i in $(seq 1 "$PODMAN_PODS"); do
        local fuzzer_seed=$RANDOM
        ( run_fuzzer_with_id_and_seed "$i" "$fuzzer_seed" ) & pid=$!
        prod_pids[${i}]=$pid
        sleep $SLEEP_BETWEEN_PODMAN_STARTUPS
    done

    for prod_pid in "${prod_pids[@]}"; do
        wait "$prod_pid"
    done
}

# ---------------------------------------------------------------------------- #

check() {

    if [[ -f "$FINDINGS_CSV" ]]; then
        cp "$FINDINGS_CSV" "$WORKSPACE_DIR/findings.csv"

        local podman_flags=(
            --volume "$DOT_CARGO":/root/.cargo
            --volume "$DOT_RUSTUP":/root/.rustup
            --volume "$DOT_ZKVM":/root/."$ZKVM_NAME"
            --volume "$ZKVM_REPO":/root/"$ZKVM_NAME"
            --volume "$WORKSPACE_DIR":/root/workspace
            --name "$CONTAINER_NAME-checker"
            --rm
            --cpus="$PODMAN_CPUS"
            --pids-limit -1
            "$IMAGE_NAME"
        )

        local fuzzer_flags=(
            --verbosity "$VERBOSITY"
            --out checker
            --zkvm "/root/$ZKVM_NAME"
            --log-file logs/checker.log
            --commit-or-branch "$COMMIT_OR_BRANCH"
        )
        [[ $TRACE_COLLECTION == true ]] && fuzzer_flags+=(--trace-collection)
        [[ $FAULT_INJECTION == true ]] && fuzzer_flags+=(--fault-injection)
        [[ $ONLY_MOD_WORD == true ]] && fuzzer_flags+=(--only-modify-word)
        [[ $NO_INLINE_ASSEMBLY == true ]] && fuzzer_flags+=(--no-inline-assembly)

        podman run "${podman_flags[@]}" "$ZKVM_NAME-fuzzer" check "/root/workspace/findings.csv" "${fuzzer_flags[@]}"
    else
        echo "Source file $FINDINGS_CSV does not exist. Skipping copy..."
    fi
}

# ---------------------------------------------------------------------------- #

interactive() {
    local flags=(
        --volume "$DOT_CARGO":/root/.cargo
        --volume "$DOT_RUSTUP":/root/.rustup
        --volume "$DOT_ZKVM":/root/."$ZKVM_NAME"
        --volume "$ZKVM_REPO":/root/"$ZKVM_NAME"
        --volume "$WORKSPACE_DIR":/root/workspace
        --name "$CONTAINER_NAME-interactive"
        --rm
        --interactive
        --tty
        --pids-limit -1
        "$IMAGE_NAME"
    )
    podman run "${flags[@]}" bash
}

# ---------------------------------------------------------------------------- #
